name: "action-release-changelog"
description: "Create a release based on the most recent changelog entry"
inputs:
  github-token:
    description: "GitHub token with permissions to create a release (content: write)"
    required: true
  repository:
    description: "The name of the repository to create the release in (e.g. outoforbitdev/action-release-changelog)"
    required: true
  changelog-file:
    description: "Filepath of the changelog file"
    default: "./CHANGELOG.md"
  draft:
    description: "Create a draft release"
    default: "true"
  write-to-summary:
    description: "Write to the workflow summary"
    default: "true"
  dry-run:
    description: "Dry run the action"
    default: "false"
outputs:
  version-short:
    description: "Short version of the release"
  version-long:
    description: "Long version of the release"
  last-version:
    description: "Last released version"
  release-link:
    description: "Link to the created release"
runs:
  using: "docker"
  image: "docker://outoforbitdev/action-release-changelog:build--1a95c67"
  args:
    - ${{ inputs.github-token }}
    - ${{ inputs.changelog-file }}
    - ${{ inputs.draft }}
    - ${{ inputs.write-to-summary }}
    - ${{ inputs.dry-run }}
    - ${{ inputs.repository }}
