name: Release
permissions: read-all
on:
  push:
    branches:
      - main
      - beta
      - dev
      - staging
jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    name: Create Github Release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Create Release
        uses: outoforbitdev/action-release-changelog@v0.0.11
        id: create-release
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
