name: Test
permissions: read-all
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
jobs:
  test-python-script:
    runs-on: ubuntu-latest
    name: Test Python Script
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.10'
      - name: Install Python dependencies
        run: python -m pip install PyGithub
      - name: Run script
        id: run-script
        run: python -m unittest discover -v -s ./src
  test-docker-image:
    runs-on: ubuntu-latest
    name: Test Image
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test image
        id: test-image
        run: |
          docker build -t image .
          docker run --entrypoint "sh" image /src/tests.sh
  test-action:
    runs-on: ubuntu-latest
    name: Test Action
    outputs:
      new-release: ${{ steps.create-release.outputs.version-long != '' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Create Release
        uses: ./
        id: create-release
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          dry-run: true
  publish-docker-image:
    runs-on: ubuntu-latest
    name: Publish Image
    needs: 
      - test-python-script
      - test-docker-image
      - test-action
    if: ${{ needs.test-action.outputs.new-release }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Publish Image
        uses: outoforbitdev/action-docker-publish@v3.0.0
        id: docker-publish
        if: github.base_ref == 'staging' || github.base_ref == 'main'
        with:
          docker-username: ${{ secrets.DOCKER_USERNAME }}
          docker-token: ${{ secrets.DOCKER_TOKEN }}
          image-name: ${{ vars.IMAGE_NAME }}
          image-tag: "build"
          platforms: "linux/amd64,linux/arm64"
