name: Test
permissions: read-all
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - src/*
jobs:
  test-python-script:
    runs-on: ubuntu-latest
    name: Test Python Script
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.10'
      - name: Install Python dependencies
        run: python -m pip install PyGithub
      - name: Run script
        id: run-script
        run: python src/create_release.py ${{ secrets.GITHUB_TOKEN }} src/test/CHANGELOG.md true true true outoforbitdev/action-release-changelog
      - name: Check outputs
        run: python src/test/check_outputs.py ${{ steps.run-script.outputs.version-short }} ${{ steps.run-script.outputs.version-long }}
  test-docker-image:
    runs-on: ubuntu-latest
    name: Test Image
    needs: test-python-script
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test Docker Image
        uses: outoforbitdev/action-docker-test@v1.0.0-staging.1
        id: docker-test
        with:
          dockerfile-path: "./src"
          test-command: "sh ./test.sh"
  publish-docker-image:
    runs-on: ubuntu-latest
    name: Publish Image
    needs: test-docker-image
    if: ${{ !contains(github.event.pull_request.labels.*.name, format('type{0} chore', ':')) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Publish Image
        uses: outoforbitdev/action-docker-publish@v3.0.0
        id: docker-publish
        if: github.base_ref == 'staging' || github.base_ref == 'main'
        with:
          docker-username: ${{ secrets.DOCKER_USERNAME }}
          docker-token: ${{ secrets.DOCKER_TOKEN }}
          image-name: ${{ vars.IMAGE_NAME }}
          image-tag: "build"
          dockerfile-path: "./src"
  test-action:
    runs-on: ubuntu-latest
    name: Test Action
    needs: test-docker-image
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Create Release
        uses: ./
        id: create-release
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          dry-run: true
