name: Test
permissions: read-all
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    name: Publish Image
    if: ${{ !contains(github.event.pull_request.labels.*.name, format('type{0} chore', ':')) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Publish Image
        uses: outoforbitdev/action-docker-publish@v3.0.0
        id: docker-publish
        if: github.base_ref == 'staging' || github.base_ref == 'main'
        with:
          docker-username: ${{ secrets.DOCKER_USERNAME }}
          docker-token: ${{ secrets.DOCKER_TOKEN }}
          image-name: ${{ vars.IMAGE_NAME }}
          image-tag: "build"
      - name: Output Tags
        run: echo "Tag is ${{steps.docker-publish.output.sha-tag}}"
